module.exports = {
    community: [
      {
        type: 'autogenerated',
        dirName: '.',
      },
      {
        type: 'link',
        label: 'Chat with us on Discord',
        href: 'https://discord.gg/docusaurus',
      },
    ],
  };